### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by YosanAI** [Immugio/three-math-extensions#2]
most of the functions in this lib, are not optimized to be called from Mousemove or other repetitive events. because most of these functions create new objects like vector and lines. I think we should use globally declared temp Objects to do the computations needed in the functions.

also there is no way to set points of an existing Line2d or Polygon without creating a new Line2d or Polygon. this makes it unefficient to call it from repetitive events like mouse move

**Comment by Immugio** [comment]
Hi @YosanAI,

You could try the following approach to reuse the object:
```
const line = new Line2D(new Vec2(0, 0), new Vec2(0, 0));

window.addEventListener("mousemove", e => {
    line.start.set(0, 0);
    line.end.set(e.clientX, e.clientY);
});
```
Does this help?

**Comment by YosanAI** [comment]
Hello @Immugio 
First of all, thanks a lot for this lib. It has a lot of helpful vec math functions.
Yes it does help for specifically creating a line. But this is more of a global problem. Most of the line functions internally create objects like vectors on each call, which makes them inefficient to call them from mousemove.

For example `projectOn`, creates a new `Vec2` and `Line2d` on each call. 
```
public projectOn(other: Line2D, clampToLine: boolean): Line2D {
        const p1 = other.closestPointToPoint(this.start, clampToLine, new Vec2());
        const p2 = other.closestPointToPoint(this.end, clampToLine, new Vec2());

        return p1.distanceTo(this.start) < p2.distanceTo(this.start) ? new Line2D(p1, p2) : new Line2D(p2, p1);
    }

```

This is just one example I quickly searched for to demonstrate the case. I have seen several function doing the same on `Line2D` and `Polygon`

**Comment by Immugio** [comment]
Hi @YosanAI,

Thank you for your views on this. I guess this is a matter of preference. A lot of functions very deliberately written in this way so that the original object stays unaltered. With this approach, new instances have to be created.

Probably a better choice would have been to modify the existing instance and rely on the user to clone it if they want to keep the original object unchanged. I will keep this in mind when developing further functionality and/or doing substantial refactoring.
